# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  param_fetcher_listener: true
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json}
      - { path: '^/', priorities: ['html'], fallback_format: json, prefer_extension: false }
  view:
    view_response_listener: 'force'
    formats:
      json: true
  exception:
    enabled: true
#  routing_loader:
#    default_format: json
#    include_format: false
#  format_listener:
#    rules:
#      - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
#      - { path: '^/student', priorities: ['html'], fallback_format: json, prefer_extension: false }
#  param_fetcher_listener: true
#  access_denied_listener:
#    json: true
#  view:
#    view_response_listener: 'force'
#    formats:
#      json: true