#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: api/login_check

students:
  resource : App\Controller\StudentController
  prefix : api

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

main:
  path: /
  controller : App\Controller\AdminController::index
