#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: api/login_check

students:
  type : rest
  resource : App\Controller\StudentController
  prefix : api
